const CHANGE_USERNAME = 'CHANGE_USERNAME';
const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
const CHANGE_KEY = 'CHANGE_KEY';
const ADD = 'ADD'

export {
    CHANGE_PASSWORD,
    CHANGE_USERNAME,
    CHANGE_KEY,
    ADD
}